[build-system]
requires = ["setuptools","wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"


[project]
name = "evutils"
dynamic = ["version"]
authors = [
  {name = "Jakub Mandula", email = "jakub.mandula@pbl.ee.ethz.ch"},
]
description = "Utilities for event-based vision"
readme = "README.md"
license = {file = "LICENSE"}
dependencies = [
    "numpy",
    "torch",
    "tqdm",
    "matplotlib",
    "opencv-python",
    "numba",
    "pandas",
]
requires-python = ">= 3.9"
keywords = ["events", "dvs", "neuromorphic", "vision", "event-based"]

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["evutils"]


[tool.setuptools_scm]
write_to = "src/evutils/_version.py"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]