name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
      - name: Download submoduels
        run: git submodule update --init --recursive
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Pytests and any other packages
        run: pip install pytest
      - name: Install package
        run: pip install .
      - name: Run Tests
        run: pytest -s -v